### ISSUE TITLE
`PrometheusExportService.addDefaults` using `CollectorRegistry.defaultRegistry` registers `jvm_classes_loaded` multiple times.

### ISSUE THREAD

**Issue by zarthross** [http4s/http4s-prometheus-metrics#63]
Below is a simple reproduction of the issue, tested with version `0.23.12`

## Reproduction
```scala 
import cats._
import cats.implicits._
import cats.effect._
import cats.effect.unsafe.implicits._
import io.prometheus.client._
import scala.jdk.CollectionConverters._
import org.http4s.metrics.prometheus._

def printCR(name: String, cr: CollectorRegistry): IO[Unit] = 
  IO.println(s"$name: ${cr.metricFamilySamples.asScala.map(_.name).take(3).mkString("\n  ")}")

def go(name: String, cr: CollectorRegistry): IO[Unit] = {
  IO.println(name) *>
    printCR(s"$name Start", cr) *>
    PrometheusExportService.addDefaults[IO](cr)
      .use { _ => 
        printCR(s"$name After", cr)
      }
  }

{
  go("New Collector", new CollectorRegistry()) *>
  go("Default Collector", CollectorRegistry.defaultRegistry) 
}.unsafeRunSync()
```

### Yields
```
New Collector
New Collector Start: 
New Collector After: jvm
  process_cpu_seconds
  process_start_time_seconds
Default Collector
Default Collector Start: 
java.lang.IllegalArgumentException: Failed to register Collector of type ClassLoadingExports: The Collector exposes the same name multiple times: jvm_classes_loaded
  at io.prometheus.client.CollectorRegistry.assertNoDuplicateNames(CollectorRegistry.java:71)
  at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:51)
  at io.prometheus.client.Collector.register(Collector.java:307)
  at org.http4s.metrics.prometheus.Prometheus$.$anonfun$registerCollector$1(Prometheus.scala:287)
  at println @ printCR(<console>:9)
  at make @ org.http4s.metrics.prometheus.Prometheus$.registerCollector(Prometheus.scala:287)
  at make @ org.http4s.metrics.prometheus.Prometheus$.registerCollector(Prometheus.scala:287)
  ... 5 elided
```

**Comment by zcox** [comment]
I'm also trying to fix this exception in several of our services. Curious if this is also reproduced in version `0.24.3`? It seems like this was [fixed](https://github.com/prometheus/client_java/pull/681) in a newer version of `simpleclient`.

**Comment by rossabaker** [comment]
I don't see where Prometheus backported a fix to 0.11.  It's not our bug, it's in an EOL version, and everyone has had a year to upgrade their dashboards.  I think this should be the kick in the tuchus to get on 0.24.

**Comment by zcox** [comment]
FWIW the cause of this runtime exception in our services seemed to be having both `simpleclient:0.16.0` and `simpleclient_hotspot:0.11.0` on the classpath together. When downgrading to `simpleclient:0.11.0` the runtime exception stopped occurring.

**Comment by rossabaker** [comment]
@zarthross Was this the case for you, too?  Are you depending on those independently, or having something transitively bump the core without hotspot?

**Comment by hamnis** [comment]
closing due to no response from requested party, reopen if this is still valid.
